definitions:
  handler.UserCreateReq:
    properties:
      age:
        maximum: 120
        minimum: 1
        type: integer
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - nickname
    - password
    - username
    type: object
  httpx.Resp:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /user:
    get:
      consumes:
      - application/json
      description: 用户列表
      parameters:
      - description: 用户ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 响应结果
          schema:
            $ref: '#/definitions/httpx.Resp'
      summary: 用户列表
      tags:
      - user
    post:
      consumes:
      - application/json
      description: 新增用户
      parameters:
      - description: body参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.UserCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应结果
          schema:
            $ref: '#/definitions/httpx.Resp'
      summary: 新增用户
      tags:
      - 分组名称
swagger: "2.0"
