definitions:
  handler.UserCreateReq:
    properties:
      avatar:
        description: 头像地址
        example: https://www.baidu.com/img/bd_logo1.png
        type: string
      birth_date:
        description: 生日 不得小于当前日期
        example: "2020-01-01"
        type: string
      care_type:
        description: '1: 身份证 2: 护照'
        enum:
        - 1
        - 2
        example: 1
        type: integer
      description:
        description: 描述
        example: 这是一段人物的描述
        type: string
      id_card:
        description: 生份证或者护照号码
        example: "123456789012345678"
        type: string
      mobile:
        description: 手机号
        example: "1389999999"
        type: string
      name:
        description: 用户姓名，不得包含特殊字符
        example: 张三
        type: string
      sex:
        description: 'M: 男性 F: 女性 O: 其他'
        enum:
        - M
        - F
        - O
        example: O
        type: string
    required:
    - avatar
    - birth_date
    - care_type
    - description
    - id_card
    - mobile
    - name
    - sex
    type: object
  handler.UserListItem:
    properties:
      avatar:
        example: https://www.baidu.com/img/bd_logo1.png
        type: string
      birth_date:
        example: "2020-01-01"
        type: string
      description:
        example: 这是一个用户
        type: string
      id_card:
        example: "123456789012345678"
        type: string
      mobile:
        example: "13888888888"
        type: string
      name:
        example: 张三
        type: string
      sex:
        description: 'M: 男性 F: 女性 O: 其他'
        enum:
        - M
        - F
        - O
        type: string
    required:
    - birth_date
    - name
    - sex
    type: object
  handler.UserListRes:
    properties:
      list:
        items:
          $ref: '#/definitions/handler.UserListItem'
        type: array
      total:
        type: integer
    type: object
  httpx.Resp:
    properties:
      code:
        description: 业务错误码,正常返回为200，错误返回为错误码
        type: integer
      data:
        description: 返回数据
      msg:
        description: 错误信息，如果状态码为200，msg为OK
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/user:
    get:
      consumes:
      - application/json
      description: 用户列表
      parameters:
      - description: 年龄
        example: 101
        in: query
        name: age
        type: integer
      - description: 生日
        example: "2020-01-01"
        in: query
        name: birthday
        type: string
      - description: 邮箱
        example: zhangsanfeng@163.com
        in: query
        name: email
        type: string
      - description: 手机号
        example: "13888888888"
        in: query
        name: mobile
        type: string
      - description: 昵称
        example: 张三疯
        in: query
        name: nickname
        type: string
      - description: 用户名
        example: 张三
        in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 响应结果
          schema:
            allOf:
            - $ref: '#/definitions/httpx.Resp'
            - properties:
                data:
                  $ref: '#/definitions/handler.UserListRes'
              type: object
      summary: 用户列表
      tags:
      - user
    post:
      consumes:
      - application/json
      description: 新增用户
      parameters:
      - description: body参数
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.UserCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应结果
          schema:
            $ref: '#/definitions/httpx.Resp'
      summary: 新增用户
      tags:
      - user
swagger: "2.0"
